directories:
  output: ./product
  buildResources: build
appId: com.electron.badzupa
productName: XBADZUPA
files:
  - filter:
      - assets
      - ./dist
      - ./dist/index.html
      - ./dist/main.js
      - package.json
      - package-lock.json
asarUnpack:
  - ./dist/data/
  - ./dist/algorithm/
  - ./node_modules/r-script
  - ./node_modules/@types/r-script
dmg:
  sign: false
mac:
  icon: icon/badzupa.png
  target:
    - dmg
win:
  icon: ./icon/todo.ico
  target: msi
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
electronVersion: 13.6.9
