# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CppLoglikelihood <- function(D, h, n) {
    .Call('_badzupa_CppLoglikelihood', PACKAGE = 'badzupa', D, h, n)
}

make_density <- function(x, D, h, n, m) {
    .Call('_badzupa_make_density', PACKAGE = 'badzupa', x, D, h, n, m)
}

make_pilot <- function(D, h, n) {
    .Call('_badzupa_make_pilot', PACKAGE = 'badzupa', D, h, n)
}

